services:
  - type: web
    name: workreports
    env: ruby
    buildCommand: |
      bundle install
      bundle exec rails db:migrate
      bundle exec rails db:migrate DATABASE=queue
    startCommand: >
      bundle exec puma -C config/puma.rb
