services:
  - type: web
    name: workreports
    env: ruby
    buildCommand: |
      bundle install
      yarn install --frozen-lockfile
      bundle exec rails assets:precompile
    startCommand: >
      bundle exec puma -C config/puma.rb
    releaseCommand: |
      bundle exec rails db:migrate
      bundle exec rails db:migrate:queue
      bundle exec rails db:migrate:cable
